# Generated by Django 5.2.8 on 2026-01-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_alter_sport_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='is_ranking',
            new_name='is_f1',
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='sport',
            name='icon',
        ),
        migrations.AddField(
            model_name='sport',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='result_text',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('SCH', 'Programado'), ('LIVE', 'En directo'), ('FIN', 'Finalizado'), ('POST', 'Aplazado')], default='SCH', max_length=8),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sport',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='F1RaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f1_events', to='sports.sport')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='time_str',
        ),
        migrations.CreateModel(
            name='F1DriverStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('driver', models.CharField(max_length=80)),
                ('team', models.CharField(blank=True, default='', max_length=80)),
                ('points', models.PositiveIntegerField(default=0)),
                ('gap', models.CharField(blank=True, default='', max_length=30)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f1_standings', to='sports.sport')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('sport', 'position')},
            },
        ),
    ]
