# Generated by Django 5.2.8 on 2026-01-07 14:25

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_alter_match_options_rename_is_ranking_sport_is_f1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f1raceevent',
            name='sport',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='emoji',
            new_name='icon',
        ),
        migrations.RemoveField(
            model_name='match',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='is_f1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sport',
        ),
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programado'), ('live', 'En directo'), ('finished', 'Finalizado')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.DeleteModel(
            name='F1DriverStanding',
        ),
        migrations.DeleteModel(
            name='F1RaceEvent',
        ),
    ]
