# Generated by Django 5.2.8 on 2026-01-07 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        ('sports', '0004_remove_f1raceevent_sport_rename_emoji_sport_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='watching_sport',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='watching_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.match'),
        ),
    ]
