# Generated by Django 5.2.8 on 2026-01-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_memberprofile_watching_sport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='watching_match',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='watching_sport_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
